Repository FutureTense/keymaster, pull requests merged in 2021-02, with the labels that each got.

#72 Change zip_file to zip_release
  hacs.json
Labels: code-quality

#73 Remove version number from const.py since its set by CI
  custom_components/keymaster/const.py
Labels: code-quality

#46 Initial zwave_js support
  custom_components/keymaster/__init__.py
  custom_components/keymaster/const.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/lock.py
  custom_components/keymaster/manifest.json
  custom_components/keymaster/services.py
  custom_components/keymaster/strings.json
  custom_components/keymaster/translations/en.json
  custom_components/keymaster/translations/nb.json
  requirements_dev.txt
Labels: feature

#74 Add zwave_js support
  assets/additional_yaml/zwave_js.yaml
  custom_components/keymaster/__init__.py
  custom_components/keymaster/config_flow.py
  custom_components/keymaster/const.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/lock.py
  custom_components/keymaster/manifest.json
  custom_components/keymaster/services.py
  custom_components/keymaster/strings.json
  custom_components/keymaster/translations/en.json
  custom_components/keymaster/translations/nb.json
  requirements_dev.txt
  requirements_test.txt
  tests/common.py
  tests/conftest.py
Labels: feature

#75 Remove Node typehint since it creates problems
  custom_components/keymaster/lock.py
Labels: bugfix

#76 Some fixes
  custom_components/keymaster/__init__.py
  custom_components/keymaster/config_flow.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/strings.json
  custom_components/keymaster/translations/en.json
Labels: bugfix

#82 Resolve KeyError at startup for zwave_js by waiting for zwave_js config entry to be set up if it hasn't been already
  custom_components/keymaster/helpers.py
Labels: bugfix

#83 Add entity ID to `keymaster_lock_state_changed` event data
  custom_components/keymaster/helpers.py
  tests/common.py
Labels: feature

#84 Fix state and event listeners and support child locks for lock state notifications
  custom_components/keymaster/__init__.py
  custom_components/keymaster/config_flow.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/services.py
  pyproject.toml
  tests/common.py
  tests/test_helpers.py
  tests/test_services.py
Labels: bugfix, feature

#86 Add raman325 to codeowner in manifest.json
  custom_components/keymaster/manifest.json
Labels: code-quality

#88 Remove initial state for input helpers and reset code slots when they are in an unknown state
  custom_components/keymaster/__init__.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/keymaster.yaml
  custom_components/keymaster/manifest.json
  custom_components/keymaster/services.py
Labels: bugfix

#91 Fix options update to only run once and fix import bug
  custom_components/keymaster/__init__.py
  custom_components/keymaster/keymaster.yaml
  custom_components/keymaster/sensor.py
  tests/conftest.py
  tests/test_init.py
Labels: bugfix

#93 Fix code slot count when generating code slot files, sensors, etc
  custom_components/keymaster/__init__.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/sensor.py
  custom_components/keymaster/services.py
Labels: bugfix

#95 Add zwave_js tests for services
  tests/test_services.py
Labels: code-quality
