Repository FutureTense/keymaster, pull requests merged in 2021-07, with the labels that each got.

#193 fix: invalid input on lockname
  custom_components/keymaster/config_flow.py
Labels: bugfix

#194 Reload timer domain
  custom_components/keymaster/helpers.py
Labels: enhancement

#198 Call correct service to reset codeslots
  custom_components/keymaster/helpers.py
  tests/conftest.py
  tests/test_binary_sensor.py
  tests/test_config_flow.py
  tests/test_helpers.py
  tests/test_init.py
  tests/test_services.py
Labels: bugfix

#203 Update notify prefix
  custom_components/keymaster/keymaster_common.yaml
Labels: breaking-change

#200 Fetch zwave-js code when it hasn't already been fetched
  custom_components/keymaster/__init__.py
  custom_components/keymaster/binary_sensor.py
  hacs.json
  requirements_dev.txt
Labels: bugfix, enhancement

#191 Add logic to refresh user codes for zwave-js
  custom_components/keymaster/__init__.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/services.py
Labels: enhancement
