Repository FutureTense/keymaster, pull requests merged in 2021-01, with the labels that each got.

#34 Add more services tests
  tests/test_services.py
Labels: code-quality

#48 Add Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
Labels: code-quality

#53 Move synchronize code slot automation logic into binary sensor to resolve one issue in #25
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/keymaster.yaml
Labels: bugfix

#54 If possible, hot reload package files when generating them
  custom_components/keymaster/services.py
Labels: feature

#45 Move reset_code_slot from script to service
  custom_components/keymaster/__init__.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/keymaster.yaml
  custom_components/keymaster/keymaster_common.yaml
  custom_components/keymaster/services.py
  custom_components/keymaster/services.yaml
  tests/test_services.py
Labels: feature

#57 Fix timezone bug
  custom_components/keymaster/helpers.py
Labels: bugfix

#58 Add zwave workaround to clear code and block on workaround service calls
  custom_components/keymaster/services.py
  tests/test_services.py
Labels: bugfix, code-quality

#59 Resubmit fix to generate packages service
  custom_components/keymaster/__init__.py
  custom_components/keymaster/services.py
  tests/test_services.py
Labels: bugfix

#60 Resubmit fix to ZWave logic
  custom_components/keymaster/helpers.py
Labels: bugfix

#63 Add v before release drafter version number to follow existing convention
  .github/release-drafter.yml
Labels: code-quality

#67 Add workflow to auto update manifest with current version
  .github/workflows/update_manifest.yaml
  custom_components/keymaster/manifest.json
Labels: code-quality

#68 Shrink package files and reduce # of entities
  assets/additional_yaml/ozw.yaml
  assets/additional_yaml/zwave.yaml
  custom_components/keymaster/config_flow.py
  custom_components/keymaster/keymaster.yaml
  custom_components/keymaster/keymaster_common.yaml
  custom_components/keymaster/services.py
  tests/test_package_files.py
Labels: code-quality

#65 Hot reload package files if possible when keymaster.generate_package service is called, and add notifications for processes that take a while
  custom_components/keymaster/__init__.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/manifest.json
  custom_components/keymaster/services.py
  tests/conftest.py
  tests/test_helpers.py
  tests/test_init.py
  tests/test_services.py
Labels: feature

#69 Bump const.py VERSION to be correct
  custom_components/keymaster/const.py
Labels: bugfix

#71 Fix release workflow
  .github/workflows/release.yaml
  .github/workflows/update_manifest.yaml
  custom_components/keymaster/manifest.json
  hacs.json
Labels: code-quality
