Repository FutureTense/keymaster, pull requests merged in 2021-04, with the labels that each got.

#147 Switch using_* logic to use entity platform
  custom_components/keymaster/__init__.py
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/lock.py
  custom_components/keymaster/services.py
  requirements_dev.txt
  tests/conftest.py
  tests/test_binary_sensor.py
  tests/test_init.py
  tests/test_services.py
Labels: enhancement

#146 Make date range accept start and stop times
  custom_components/keymaster/keymaster.yaml
Labels: feature

#142 Handle event changes in 2021.4
  custom_components/keymaster/__init__.py
  custom_components/keymaster/helpers.py
  hacs.json
  requirements_dev.txt
Labels: breaking-change, bugfix

#152 Update notification logic
  custom_components/keymaster/keymaster_common.yaml
Labels: enhancement
