Repository FutureTense/keymaster, pull requests merged in 2021-03, with the labels that each got.

#85 Add new keymaster_zwave_network_ready binary sensor to replace pre-installation steps entities
  custom_components/keymaster/__init__.py
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/const.py
  custom_components/keymaster/exceptions.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/keymaster.yaml
  custom_components/keymaster/keymaster_common.yaml
  custom_components/keymaster/sensor.py
  custom_components/keymaster/services.py
  hacs.json
  tests/test_helpers.py
  tests/test_package_files.py
Labels: enhancement

#104 Guard against creating multiple binary_sensors
  custom_components/keymaster/binary_sensor.py
Labels: bugfix

#106 Handle if alarm level or alarm type state is unknown
  custom_components/keymaster/helpers.py
Labels: bugfix

#108 Update test data for invalid code
  tests/const.py
  tests/json/lock.json
  tests/json/zwave_js/lock_kwikset_910_state.json
  tests/json/zwave_js/lock_schlage_be469_state.json
  tests/test_config_flow.py
  tests/test_helpers.py
  tests/test_init.py
  tests/test_services.py
Labels: code-quality

#110 Fix pin synchronization issue
  custom_components/keymaster/keymaster.yaml
Labels: bugfix

#102 Updates for HA 2021.3.0
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/sensor.py
  custom_components/keymaster/services.yaml
  hacs.json
Labels: breaking-change, enhancement

#113 Guard against unavailable state as well
  custom_components/keymaster/helpers.py
Labels: bugfix

#114 Fix 2021.3 services.yaml schema
  custom_components/keymaster/services.yaml
Labels: bugfix

#115 Fix network ready duplicate sensor issue
  custom_components/keymaster/__init__.py
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/services.yaml
Labels: breaking-change, bugfix

#119 Fix synchronization automation
  custom_components/keymaster/keymaster.yaml
Labels: bugfix

#120 Adjust zwave test
  tests/test_init.py
Labels: code-quality

#122 More test adjustments
  tests/test_services.py
Labels: code-quality

#123 Create binary_sensor test
  tests/test_binary_sensor.py
Labels: code-quality

#124 Adjust helpers test
  tests/test_helpers.py
Labels: code-quality

#127 Additional init and config_flow tests
  .coveragerc
  tests/test_config_flow.py
  tests/test_init.py
Labels: code-quality

#130 Fix access count decrement for zwave_js notification events
  custom_components/keymaster/const.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/keymaster_common.yaml
Labels: bugfix

#131 Make lock name a required field for generate_package service
  custom_components/keymaster/services.yaml
Labels: bugfix

#135 Check active binary sensor instead of enabled input boolean for workaround logic
  custom_components/keymaster/__init__.py
Labels: bugfix
