Repository FutureTense/keymaster, pull requests merged in 2021-06, with the labels that each got.

#177 Initialize child locks after package generation
  custom_components/keymaster/services.py
  custom_components/keymaster/strings.json
  custom_components/keymaster/translations/en.json
  custom_components/keymaster/translations/nb.json
Labels: enhancement

#178 Call init_child_locks on startup
  custom_components/keymaster/__init__.py
  custom_components/keymaster/services.py
Labels: bugfix

#179 More child lock fixes
  custom_components/keymaster/__init__.py
  custom_components/keymaster/config_flow.py
  custom_components/keymaster/services.py
  tests/common.py
  tests/conftest.py
Labels: bugfix, code-quality

#181 Fixes reversed enabled boolen
  custom_components/keymaster/keymaster_common.yaml
  custom_components/keymaster/keymaster_common_child.yaml
Labels: bugfix

#186 fix: Add checks before calling init_child_locks
  custom_components/keymaster/__init__.py
  custom_components/keymaster/services.py
Labels: bugfix
