Repository FutureTense/keymaster, pull requests merged in 2021-05, with the labels that each got.

#161 Fix broken test and speed up test_update_usercodes_using_ozw
  tests/test_binary_sensor.py
  tests/test_helpers.py
  tests/test_init.py
  tests/test_package_files.py
  tests/test_services.py
Labels: code-quality

#166 Fix: Reset date range start/end times
  custom_components/keymaster/keymaster_common.yaml
Labels: bugfix

#167 Add additional categories to release drafter
  .github/release-drafter.yml
Labels: repo

#170 Child locks refactor
  custom_components/keymaster/__init__.py
  custom_components/keymaster/config_flow.py
  custom_components/keymaster/const.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/keymaster_child.yaml
  custom_components/keymaster/keymaster_common_child.yaml
  custom_components/keymaster/lock.py
  custom_components/keymaster/lovelace_child.code
  custom_components/keymaster/lovelace_child.head
  custom_components/keymaster/manifest.json
  custom_components/keymaster/services.py
  tests/const.py
  tests/test_config_flow.py
Labels: breaking-change, feedback-requested
