Repository FutureTense/keymaster, pull requests merged in 2022-05, with the labels that each got.

#277 Remove zwave and ozw support
  .coveragerc
  custom_components/keymaster/__init__.py
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/config_flow.py
  custom_components/keymaster/const.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/sensor.py
  custom_components/keymaster/services.py
  requirements_dev.txt
  tests/common.py
  tests/conftest.py
  tests/json/lock.json
  tests/json/zwave_js/controller_state.json
  tests/json/zwave_js/lock_kwikset_910_state.json
  tests/json/zwave_js/lock_schlage_be469_state.json
  tests/mock/zwave.py
  tests/test_binary_sensor.py
  tests/test_config_flow.py
  tests/test_helpers.py
  tests/test_init.py
  tests/test_services.py
Labels: code-quality, breaking-change

#282 fix: add FE599 lock 'user access' code to `alarmType` map
  .github/workflows/pytest.yaml
  custom_components/keymaster/const.py
  hacs.json
  requirements_test.txt
  tests/common.py
  tests/conftest.py
  tests/test_config_flow.py
  tests/test_helpers.py
Labels: bugfix, code-quality

#279 Bump minimum version of HA required
  hacs.json
Labels: code-quality
