Repository FutureTense/keymaster, pull requests merged in 2024-06, with the labels that each got.

#372 fix: use config entry runtime_data to get `zwave_js` client
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/helpers.py
Labels: bugfix, breaking-change

#376 fix: handle multiple z-wave networks
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/helpers.py
Labels: bugfix

#378 refactor: switch to `async_forward_entry_setups` for HA 2024.7.x+
  custom_components/keymaster/__init__.py
Labels: code-quality
