Repository FutureTense/keymaster, pull requests merged in 2024-05, with the labels that each got.

#362 fix: maintenance fix for HA 2024.5.0b0
  .github/workflows/combined.yaml
  .github/workflows/pytest.yaml
  .github/workflows/release.yaml
  custom_components/keymaster/__init__.py
  custom_components/keymaster/binary_sensor.py
  custom_components/keymaster/config_flow.py
  custom_components/keymaster/const.py
  custom_components/keymaster/exceptions.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/lock.py
  custom_components/keymaster/manifest.json
  custom_components/keymaster/sensor.py
  custom_components/keymaster/services.py
  custom_components/keymaster/system_health.py
  hacs.json
  tests/common.py
  tests/conftest.py
  tests/test_binary_sensor.py
  tests/test_config_flow.py
  tests/test_helpers.py
  tests/test_init.py
  tests/test_package_files.py
  tests/test_services.py
Labels: code-quality, breaking-change

#363 fix: state change event function call
  custom_components/keymaster/__init__.py
Labels: bugfix

#364 fix: `handle_state_change` updated for new state change event
  .github/workflows/pytest.yaml
  .gitignore
  custom_components/keymaster/__init__.py
  custom_components/keymaster/helpers.py
  pylintrc
  requirements_test.txt
  setup.cfg
  tests/test_config_flow.py
  tox.ini
Labels: bugfix, breaking-change

#365 fix: add `callback` decorator to `handle_state_change`
  custom_components/keymaster/__init__.py
  custom_components/keymaster/const.py
  custom_components/keymaster/helpers.py
  custom_components/keymaster/services.py
  custom_components/keymaster/system_health.py
  requirements_test.txt
Labels: bugfix

#367 fix: handle `None` events
  custom_components/keymaster/helpers.py
Labels: bugfix

#368 fix: add unique_id to template yaml entities
  custom_components/keymaster/keymaster.yaml
  custom_components/keymaster/keymaster_child.yaml
  custom_components/keymaster/keymaster_common.yaml
  custom_components/keymaster/keymaster_common_child.yaml
Labels: enhancement
